"""drop total_marks from Quiz

Revision ID: 1cf5419c5c4f
Revises: 8964ae7c4721
Create Date: 2025-07-15 14:54:54.627538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf5419c5c4f'
down_revision = '8964ae7c4721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('total_marks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_marks', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
