"""add marks column to Question

Revision ID: 252fdd0a357a
Revises: 1cf5419c5c4f
Create Date: 2025-07-15 14:56:05.312551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252fdd0a357a'
down_revision = '1cf5419c5c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('marks')

    # ### end Alembic commands ###
