"""Remove num_questions column from Quiz

Revision ID: 8964ae7c4721
Revises: 
Create Date: 2025-07-15 11:58:55.260001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8964ae7c4721'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('num_questions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_questions', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
